/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/hybridUseBenefitRevisionMappers";
import * as Parameters from "../models/parameters";
import { softwareplanClientContext } from "../softwareplanClientContext";

/** Class representing a HybridUseBenefitRevision. */
export class HybridUseBenefitRevision {
  private readonly client: softwareplanClientContext;

  /**
   * Create a HybridUseBenefitRevision.
   * @param {softwareplanClientContext} client Reference to the service client.
   */
  constructor(client: softwareplanClientContext) {
    this.client = client;
  }

  /**
   * Gets the version history of a hybrid use benefit
   * @param scope The scope at which the operation is performed. This is limited to
   * Microsoft.Compute/virtualMachines and Microsoft.Compute/hostGroups/hosts for now
   * @param planId This is a unique identifier for a plan. Should be a guid.
   * @param [options] The optional parameters
   * @returns Promise<Models.HybridUseBenefitRevisionListResponse>
   */
  list(scope: string, planId: string, options?: msRest.RequestOptionsBase): Promise<Models.HybridUseBenefitRevisionListResponse>;
  /**
   * @param scope The scope at which the operation is performed. This is limited to
   * Microsoft.Compute/virtualMachines and Microsoft.Compute/hostGroups/hosts for now
   * @param planId This is a unique identifier for a plan. Should be a guid.
   * @param callback The callback
   */
  list(scope: string, planId: string, callback: msRest.ServiceCallback<Models.HybridUseBenefitListResult>): void;
  /**
   * @param scope The scope at which the operation is performed. This is limited to
   * Microsoft.Compute/virtualMachines and Microsoft.Compute/hostGroups/hosts for now
   * @param planId This is a unique identifier for a plan. Should be a guid.
   * @param options The optional parameters
   * @param callback The callback
   */
  list(scope: string, planId: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.HybridUseBenefitListResult>): void;
  list(scope: string, planId: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.HybridUseBenefitListResult>, callback?: msRest.ServiceCallback<Models.HybridUseBenefitListResult>): Promise<Models.HybridUseBenefitRevisionListResponse> {
    return this.client.sendOperationRequest(
      {
        scope,
        planId,
        options
      },
      listOperationSpec,
      callback) as Promise<Models.HybridUseBenefitRevisionListResponse>;
  }

  /**
   * Gets the version history of a hybrid use benefit
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param [options] The optional parameters
   * @returns Promise<Models.HybridUseBenefitRevisionListNextResponse>
   */
  listNext(nextPageLink: string, options?: msRest.RequestOptionsBase): Promise<Models.HybridUseBenefitRevisionListNextResponse>;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param callback The callback
   */
  listNext(nextPageLink: string, callback: msRest.ServiceCallback<Models.HybridUseBenefitListResult>): void;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param options The optional parameters
   * @param callback The callback
   */
  listNext(nextPageLink: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.HybridUseBenefitListResult>): void;
  listNext(nextPageLink: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.HybridUseBenefitListResult>, callback?: msRest.ServiceCallback<Models.HybridUseBenefitListResult>): Promise<Models.HybridUseBenefitRevisionListNextResponse> {
    return this.client.sendOperationRequest(
      {
        nextPageLink,
        options
      },
      listNextOperationSpec,
      callback) as Promise<Models.HybridUseBenefitRevisionListNextResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "{scope}/providers/Microsoft.SoftwarePlan/hybridUseBenefits/{planId}/revisions",
  urlParameters: [
    Parameters.scope,
    Parameters.planId
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.HybridUseBenefitListResult
    },
    default: {
      bodyMapper: Mappers.ErrorModel
    }
  },
  serializer
};

const listNextOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  baseUrl: "https://management.azure.com",
  path: "{nextLink}",
  urlParameters: [
    Parameters.nextPageLink
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.HybridUseBenefitListResult
    },
    default: {
      bodyMapper: Mappers.ErrorModel
    }
  },
  serializer
};
