/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { softwareplanClientContext } from "./softwareplanClientContext";


class softwareplanClient extends softwareplanClientContext {
  // Operation groups
  softwarePlan: operations.SoftwarePlan;
  hybridUseBenefit: operations.HybridUseBenefit;
  hybridUseBenefitRevision: operations.HybridUseBenefitRevision;
  operations: operations.Operations;

  /**
   * Initializes a new instance of the softwareplanClient class.
   * @param credentials Credentials needed for the client to connect to Azure.
   * @param subscriptionId The ID of the target subscription.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, subscriptionId: string, options?: Models.softwareplanClientOptions) {
    super(credentials, subscriptionId, options);
    this.softwarePlan = new operations.SoftwarePlan(this);
    this.hybridUseBenefit = new operations.HybridUseBenefit(this);
    this.hybridUseBenefitRevision = new operations.HybridUseBenefitRevision(this);
    this.operations = new operations.Operations(this);
  }
}

// Operation Specifications

export {
  softwareplanClient,
  softwareplanClientContext,
  Models as softwareplanModels,
  Mappers as softwareplanMappers
};
export * from "./operations";
