/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { BaseResource, CloudError, AzureServiceClientOptions } from "@azure/ms-rest-azure-js";
import * as msRest from "@azure/ms-rest-js";

export { BaseResource, CloudError };


/**
 * @interface
 * An interface representing Resource.
 * @extends BaseResource
 */
export interface Resource extends BaseResource {
  /**
   * @member {string} [id] Resource Id
   */
  id?: string;
  /**
   * @member {string} [name] Resource Name
   */
  name?: string;
  /**
   * @member {string} [kind] Kind of resource
   */
  kind?: string;
  /**
   * @member {string} location Resource Location
   */
  location: string;
  /**
   * @member {string} [type] Resource type
   */
  type?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] Resource tags
   */
  tags?: { [propertyName: string]: string };
}

/**
 * @interface
 * An interface representing GeneralApiInformation.
 * General API information
 *
 * @extends Resource
 */
export interface GeneralApiInformation extends Resource {
  /**
   * @member {string} [iconUrl] Icon Url
   */
  iconUrl?: string;
  /**
   * @member {string} [displayName] Display Name
   */
  displayName?: string;
  /**
   * @member {string} [description] Description
   */
  description?: string;
  /**
   * @member {string} [termsOfUseUrl] a public accessible url of the Terms Of
   * Use Url of this API
   */
  termsOfUseUrl?: string;
  /**
   * @member {string} [connectionDisplayName] DefaultConnectionNameTemplate
   */
  connectionDisplayName?: string;
  /**
   * @member {any} [connectionPortalUrl] ConnectionPortalUrl
   */
  connectionPortalUrl?: any;
}

/**
 * @interface
 * An interface representing ApiPolicies.
 * API policies
 *
 * @extends Resource
 */
export interface ApiPolicies extends Resource {
  /**
   * @member {string} [content] Content of xml policy
   */
  content?: string;
}

/**
 * @interface
 * An interface representing HostingEnvironmentServiceDescriptions.
 * Back end service per ASE
 *
 */
export interface HostingEnvironmentServiceDescriptions {
  /**
   * @member {string} [hostingEnvironmentId] Hosting environment Id
   */
  hostingEnvironmentId?: string;
  /**
   * @member {string} [hostId] Host Id
   */
  hostId?: string;
  /**
   * @member {string} [serviceUrl] service url to use
   */
  serviceUrl?: string;
  /**
   * @member {boolean} [useInternalRouting] When the backend url is in same
   * ASE, for performance reason this flag can be set to true
   * If WebApp.DisableHostNames is also set it improves the security by making
   * the back end accessible only
   * via API calls
   * Note: calls will fail if this option is used but back end is not on the
   * same ASE
   */
  useInternalRouting?: boolean;
}

/**
 * @interface
 * An interface representing BackendServiceDefinition.
 * API definitions with backend urls
 *
 * @extends Resource
 */
export interface BackendServiceDefinition extends Resource {
  /**
   * @member {string} [serviceUrl] Url from which the swagger payload will be
   * fetched
   */
  serviceUrl?: string;
  /**
   * @member {HostingEnvironmentServiceDescriptions[]}
   * [hostingEnvironmentServiceUrls] Service Urls per Hosting environment
   */
  hostingEnvironmentServiceUrls?: HostingEnvironmentServiceDescriptions[];
}

/**
 * @interface
 * An interface representing ApiOAuthSettingsParameter.
 * OAuth Settings Parameter
 *
 */
export interface ApiOAuthSettingsParameter {
  /**
   * @member {string} [value] Value
   */
  value?: string;
  /**
   * @member {any} [options] Read only: Options available to this parameter
   */
  options?: any;
  /**
   * @member {any} [uiDefinition] UI definitions per culture as caller can
   * specify the culture
   */
  uiDefinition?: any;
}

/**
 * @interface
 * An interface representing ApiOAuthSettings.
 * OAuth settings for the connection provider
 *
 */
export interface ApiOAuthSettings {
  /**
   * @member {string} [identityProvider] Identity provider
   */
  identityProvider?: string;
  /**
   * @member {string} [clientId] Resource provider client id
   */
  clientId?: string;
  /**
   * @member {string} [clientSecret] Client Secret needed for OAuth
   */
  clientSecret?: string;
  /**
   * @member {string[]} [scopes] OAuth scopes
   */
  scopes?: string[];
  /**
   * @member {string} [redirectUrl] Url
   */
  redirectUrl?: string;
  /**
   * @member {any} [properties] Read only properties for this oauth setting.
   */
  properties?: any;
  /**
   * @member {{ [propertyName: string]: ApiOAuthSettingsParameter }}
   * [customParameters] OAuth parameters key is the name of parameter
   */
  customParameters?: { [propertyName: string]: ApiOAuthSettingsParameter };
}

/**
 * @interface
 * An interface representing ConnectionParameter.
 * connection provider parameters
 *
 */
export interface ConnectionParameter {
  /**
   * @member {ConnectionParameterType} [type] Type of the parameter. Possible
   * values include: 'string', 'securestring', 'secureobject', 'int', 'bool',
   * 'object', 'array', 'oauthSetting', 'connection'
   */
  type?: ConnectionParameterType;
  /**
   * @member {any} [defaultValue] Default parameter value
   */
  defaultValue?: any;
  /**
   * @member {ApiOAuthSettings} [oAuthSettings] Settings defining OAuth flow
   * for the back end provider
   */
  oAuthSettings?: ApiOAuthSettings;
  /**
   * @member {any} [uiDefinition] UI definitions
   */
  uiDefinition?: any;
}

/**
 * @interface
 * An interface representing ApiEntity.
 * API Management
 *
 * @extends Resource
 */
export interface ApiEntity extends Resource {
  /**
   * @member {string} [apiEntityName] Name of the API
   * the URL path of this API when exposed via APIM
   */
  apiEntityName?: string;
  /**
   * @member {GeneralApiInformation} [generalInformation] the URL path of this
   * API when exposed via APIM
   */
  generalInformation?: GeneralApiInformation;
  /**
   * @member {string} [path] the URL path of this API when exposed via APIM
   */
  path?: string;
  /**
   * @member {string[]} [runtimeUrls] Read only property returning the runtime
   * endpoints where the API can be called
   */
  runtimeUrls?: string[];
  /**
   * @member {string[]} [protocols] Protocols supported by the front end -
   * http/https
   */
  protocols?: string[];
  /**
   * @member {ApiPolicies} [policies] API policies
   */
  policies?: ApiPolicies;
  /**
   * @member {BackendServiceDefinition} [backendService] Backend service
   * definition
   */
  backendService?: BackendServiceDefinition;
  /**
   * @member {string} [apiDefinitionUrl] API definition Url - url where the
   * swagger can be downloaded from
   */
  apiDefinitionUrl?: string;
  /**
   * @member {any} [metadata] Free form object for the data caller wants to
   * store
   */
  metadata?: any;
  /**
   * @member {string[]} [capabilities] Capabilities
   */
  capabilities?: string[];
  /**
   * @member {{ [propertyName: string]: ConnectionParameter }}
   * [connectionParameters] Connection parameters
   */
  connectionParameters?: { [propertyName: string]: ConnectionParameter };
  /**
   * @member {Date} [createdTime] Timestamp of the connection creation
   */
  createdTime?: Date;
  /**
   * @member {Date} [changedTime] Timestamp of last connection change.
   */
  changedTime?: Date;
}

/**
 * @interface
 * An interface representing ConnectionError.
 * Connection error
 *
 * @extends Resource
 */
export interface ConnectionError extends Resource {
  /**
   * @member {string} [code] code of the status
   */
  code?: string;
  /**
   * @member {string} [message] Description of the status
   */
  message?: string;
}

/**
 * @interface
 * An interface representing ConnectionStatus.
 * Connection status
 *
 * @extends Resource
 */
export interface ConnectionStatus extends Resource {
  /**
   * @member {string} [status] Status
   */
  status?: string;
  /**
   * @member {string} [target] Target of the error
   */
  target?: string;
  /**
   * @member {ConnectionError} [error] Error details
   */
  error?: ConnectionError;
}

/**
 * @interface
 * An interface representing CustomLoginSettingValue.
 * Custom logging setting value
 *
 * @extends Resource
 */
export interface CustomLoginSettingValue extends Resource {
  /**
   * @member {string} [option] Option selected for this custom login setting
   * value
   */
  option?: string;
}

/**
 * @interface
 * An interface representing ParameterCustomLoginSettingValues.
 * Custom logging setting values
 *
 * @extends Resource
 */
export interface ParameterCustomLoginSettingValues extends Resource {
  /**
   * @member {{ [propertyName: string]: CustomLoginSettingValue }}
   * [customParameters] Custom parameters.
   */
  customParameters?: { [propertyName: string]: CustomLoginSettingValue };
}

/**
 * @interface
 * An interface representing ArmPlan.
 * The plan object in an ARM, represents a marketplace plan
 *
 */
export interface ArmPlan {
  /**
   * @member {string} [name] The name
   */
  name?: string;
  /**
   * @member {string} [publisher] The publisher
   */
  publisher?: string;
  /**
   * @member {string} [product] The product
   */
  product?: string;
  /**
   * @member {string} [promotionCode] The promotion code
   */
  promotionCode?: string;
  /**
   * @member {string} [version] Version of product
   */
  version?: string;
}

/**
 * @interface
 * An interface representing SkuDescription.
 * Describes a sku for a scalable resource
 *
 */
export interface SkuDescription {
  /**
   * @member {string} [name] Name of the resource sku
   */
  name?: string;
  /**
   * @member {string} [tier] Service Tier of the resource sku
   */
  tier?: string;
  /**
   * @member {string} [size] Size specifier of the resource sku
   */
  size?: string;
  /**
   * @member {string} [family] Family code of the resource sku
   */
  family?: string;
  /**
   * @member {number} [capacity] Current number of instances assigned to the
   * resource
   */
  capacity?: number;
}

/**
 * @interface
 * An interface representing ResponseMessageEnvelopeApiEntity.
 * Message envelope that contains the common Azure resource manager properties
 * and the resource provider specific content
 *
 */
export interface ResponseMessageEnvelopeApiEntity {
  /**
   * @member {string} [id] Resource Id. Typically id is populated only for
   * responses to GET requests. Caller is responsible for passing in this
   * value for GET requests only.
   * For example:
   * /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupId}/providers/Microsoft.Web/sites/{sitename}
   */
  id?: string;
  /**
   * @member {string} [name] Name of resource
   */
  name?: string;
  /**
   * @member {string} [type] Type of resource e.g Microsoft.Web/sites
   */
  type?: string;
  /**
   * @member {string} [location] Geo region resource belongs to e.g.
   * SouthCentralUS, SouthEastAsia
   */
  location?: string;
  /**
   * @member {{ [propertyName: string]: string }} [tags] Tags associated with
   * resource
   */
  tags?: { [propertyName: string]: string };
  /**
   * @member {ArmPlan} [plan] Azure resource manager plan
   */
  plan?: ArmPlan;
  /**
   * @member {ApiEntity} [properties] Resource specific properties
   */
  properties?: ApiEntity;
  /**
   * @member {SkuDescription} [sku] Sku description of the resource
   */
  sku?: SkuDescription;
}

/**
 * @interface
 * An interface representing ExpandedParentApiEntity.
 * expanded parent object for expansion
 *
 * @extends Resource
 */
export interface ExpandedParentApiEntity extends Resource {
  /**
   * @member {string} [expandedParentApiEntityId] Id of connection provider
   */
  expandedParentApiEntityId?: string;
  /**
   * @member {ResponseMessageEnvelopeApiEntity} [entity] Id of connection
   * provider
   */
  entity?: ResponseMessageEnvelopeApiEntity;
}

/**
 * @interface
 * An interface representing Connection.
 * API Connection
 *
 * @extends Resource
 */
export interface Connection extends Resource {
  /**
   * @member {string} [connectionName] connection name
   */
  connectionName?: string;
  /**
   * @member {string} [displayName] display name
   */
  displayName?: string;
  /**
   * @member {ConnectionStatus[]} [statuses] Status of the connection
   */
  statuses?: ConnectionStatus[];
  /**
   * @member {{ [propertyName: string]: ParameterCustomLoginSettingValues }}
   * [customParameterValues] Custom login setting values.
   */
  customParameterValues?: { [propertyName: string]: ParameterCustomLoginSettingValues };
  /**
   * @member {string} [tenantId]
   */
  tenantId?: string;
  /**
   * @member {{ [propertyName: string]: any }} [parameterValues] Tokens/Claim
   */
  parameterValues?: { [propertyName: string]: any };
  /**
   * @member {{ [propertyName: string]: any }} [nonSecretParameterValues]
   * Tokens/Claim
   */
  nonSecretParameterValues?: { [propertyName: string]: any };
  /**
   * @member {any} [metadata]
   */
  metadata?: any;
  /**
   * @member {Date} [firstExpirationTime] Time in UTC when the first expiration
   * of OAuth tokens
   */
  firstExpirationTime?: Date;
  /**
   * @member {string[]} [keywords] List of Keywords that tag the acl
   */
  keywords?: string[];
  /**
   * @member {Date} [createdTime] Timestamp of the connection creation
   */
  createdTime?: Date;
  /**
   * @member {Date} [changedTime] Timestamp of last connection change.
   */
  changedTime?: Date;
  /**
   * @member {ExpandedParentApiEntity} [api] expanded connection provider name
   */
  api?: ExpandedParentApiEntity;
}

/**
 * @interface
 * An interface representing ConsentLinkInputParameter.
 */
export interface ConsentLinkInputParameter {
  /**
   * @member {PrincipalType} [principalType] Principal type. Possible values
   * include: 'ActiveDirectory', 'Connection', 'MicrosoftAccount'
   */
  principalType?: PrincipalType;
  /**
   * @member {string} [tenantId] Tenant Id
   */
  tenantId?: string;
  /**
   * @member {string} [objectId] AAD OID (user or group) if the principal type
   * is ActiveDirectory.
   * MSA PUID if the principal type is MicrosoftAccount.
   */
  objectId?: string;
  /**
   * @member {string} [parameterName] Name of the parameter in the connection
   * provider's oauthSettings
   */
  parameterName?: string;
  /**
   * @member {string} [redirectUrl] Name of the parameter in the connection
   * provider's oauthSettings
   */
  redirectUrl?: string;
}

/**
 * @interface
 * An interface representing ConsentLinkInput.
 * Connection Consent Link payload
 *
 * @extends Resource
 */
export interface ConsentLinkInput extends Resource {
  /**
   * @member {ConsentLinkInputParameter[]} [parameters] Array of links
   */
  parameters?: ConsentLinkInputParameter[];
}

/**
 * @interface
 * An interface representing ConsentLink.
 */
export interface ConsentLink {
  /**
   * @member {string} [link] Uri for the consent link
   */
  link?: string;
  /**
   * @member {string} [firstPartyLoginUri] Uri for first party login
   */
  firstPartyLoginUri?: string;
  /**
   * @member {string} [displayName] Display Name of the parameter in the
   * connection provider's oauthSettings
   */
  displayName?: string;
  /**
   * @member {LinkState} [status] Status of the link. Possible values include:
   * 'Unauthenticated', 'Authenticated', 'Error'
   */
  status?: LinkState;
}

/**
 * @interface
 * An interface representing ConsentLinkPayload.
 * Collection of consent links
 *
 */
export interface ConsentLinkPayload {
  /**
   * @member {ConsentLink[]} [value] Collection of resources
   */
  value?: ConsentLink[];
}

/**
 * @interface
 * An interface representing ListConnectionKeysInput.
 * List Connection Keys Input payload
 *
 * @extends Resource
 */
export interface ListConnectionKeysInput extends Resource {
  /**
   * @member {string} [validityTimeSpan] time span for how long the keys will
   * be valid
   */
  validityTimeSpan?: string;
}

/**
 * @interface
 * An interface representing ConnectionSecrets.
 */
export interface ConnectionSecrets {
  /**
   * @member {{ [propertyName: string]: any }} [parameterValues] Tokens/Claim
   */
  parameterValues?: { [propertyName: string]: any };
  /**
   * @member {string} [connectionKey] Connection Key
   */
  connectionKey?: string;
}

/**
 * @interface
 * An interface representing ConfirmConsentCodeInput.
 * Confirm Consent Code Input payload
 *
 * @extends Resource
 */
export interface ConfirmConsentCodeInput extends Resource {
  /**
   * @member {PrincipalType} [principalType] Principal type. Possible values
   * include: 'ActiveDirectory', 'Connection', 'MicrosoftAccount'
   */
  principalType?: PrincipalType;
  /**
   * @member {string} [tenantId] Tenant Id
   */
  tenantId?: string;
  /**
   * @member {string} [objectId] AAD object ID. This is userId
   */
  objectId?: string;
  /**
   * @member {string} [code] Code that was returned during consent flow
   */
  code?: string;
}

/**
 * @interface
 * An interface representing ManagedApisGetOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface ManagedApisGetOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {boolean} [exportParameter] flag showing whether to export API
   * definition in format specified by Accept header.
   */
  exportParameter?: boolean;
}

/**
 * @interface
 * An interface representing ConnectionsListOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface ConnectionsListOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {number} [top] The number of items to be included in the result.
   */
  top?: number;
  /**
   * @member {string} [filter] The filter to apply on the operation.
   */
  filter?: string;
}

/**
 * @interface
 * An interface representing WebSiteManagementClientOptions.
 * @extends AzureServiceClientOptions
 */
export interface WebSiteManagementClientOptions extends AzureServiceClientOptions {
  /**
   * @member {string} [baseUri]
   */
  baseUri?: string;
}


/**
 * @interface
 * An interface representing the ApisCollection.
 * Collection of Apis
 *
 * @extends Array<ApiEntity>
 */
export interface ApisCollection extends Array<ApiEntity> {
  /**
   * @member {string} [nextLink] Link to next page of resources
   */
  nextLink?: string;
}

/**
 * @interface
 * An interface representing the ConnectionCollection.
 * Collection of connections
 *
 * @extends Array<Connection>
 */
export interface ConnectionCollection extends Array<Connection> {
  /**
   * @member {string} [nextLink] Link to next page of resources
   */
  nextLink?: string;
}

/**
 * Defines values for ConnectionParameterType.
 * Possible values include: 'string', 'securestring', 'secureobject', 'int', 'bool', 'object',
 * 'array', 'oauthSetting', 'connection'
 * @readonly
 * @enum {string}
 */
export type ConnectionParameterType = 'string' | 'securestring' | 'secureobject' | 'int' | 'bool' | 'object' | 'array' | 'oauthSetting' | 'connection';

/**
 * Defines values for PrincipalType.
 * Possible values include: 'ActiveDirectory', 'Connection', 'MicrosoftAccount'
 * @readonly
 * @enum {string}
 */
export type PrincipalType = 'ActiveDirectory' | 'Connection' | 'MicrosoftAccount';

/**
 * Defines values for LinkState.
 * Possible values include: 'Unauthenticated', 'Authenticated', 'Error'
 * @readonly
 * @enum {string}
 */
export type LinkState = 'Unauthenticated' | 'Authenticated' | 'Error';

/**
 * Contains response data for the list operation.
 */
export type ManagedApisListResponse = ApisCollection & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ApisCollection;
    };
};

/**
 * Contains response data for the get operation.
 */
export type ManagedApisGetResponse = ApiEntity & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ApiEntity;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type ManagedApisListNextResponse = ApisCollection & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ApisCollection;
    };
};

/**
 * Contains response data for the list operation.
 */
export type ConnectionsListResponse = ConnectionCollection & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConnectionCollection;
    };
};

/**
 * Contains response data for the get operation.
 */
export type ConnectionsGetResponse = Connection & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Connection;
    };
};

/**
 * Contains response data for the createOrUpdate operation.
 */
export type ConnectionsCreateOrUpdateResponse = Connection & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Connection;
    };
};

/**
 * Contains response data for the listConsentLinks operation.
 */
export type ConnectionsListConsentLinksResponse = ConsentLinkPayload & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConsentLinkPayload;
    };
};

/**
 * Contains response data for the confirmConsentCode operation.
 */
export type ConnectionsConfirmConsentCodeResponse = Connection & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Connection;
    };
};

/**
 * Contains response data for the listConnectionKeys operation.
 */
export type ConnectionsListConnectionKeysResponse = ConnectionSecrets & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConnectionSecrets;
    };
};

/**
 * Contains response data for the listNext operation.
 */
export type ConnectionsListNextResponse = ConnectionCollection & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: ConnectionCollection;
    };
};
