/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { CloudErrorMapper, BaseResourceMapper } from "@azure/ms-rest-azure-js";
import * as msRest from "@azure/ms-rest-js";

export const CloudError = CloudErrorMapper;
export const BaseResource = BaseResourceMapper;

export const Resource: msRest.CompositeMapper = {
  serializedName: "Resource",
  type: {
    name: "Composite",
    className: "Resource",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      kind: {
        serializedName: "kind",
        type: {
          name: "String"
        }
      },
      location: {
        required: true,
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const GeneralApiInformation: msRest.CompositeMapper = {
  serializedName: "GeneralApiInformation",
  type: {
    name: "Composite",
    className: "GeneralApiInformation",
    modelProperties: {
      ...Resource.type.modelProperties,
      iconUrl: {
        serializedName: "properties.iconUrl",
        type: {
          name: "String"
        }
      },
      displayName: {
        serializedName: "properties.displayName",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "properties.description",
        type: {
          name: "String"
        }
      },
      termsOfUseUrl: {
        serializedName: "properties.termsOfUseUrl",
        type: {
          name: "String"
        }
      },
      connectionDisplayName: {
        serializedName: "properties.connectionDisplayName",
        type: {
          name: "String"
        }
      },
      connectionPortalUrl: {
        serializedName: "properties.connectionPortalUrl",
        type: {
          name: "Object"
        }
      }
    }
  }
};

export const ApiPolicies: msRest.CompositeMapper = {
  serializedName: "ApiPolicies",
  type: {
    name: "Composite",
    className: "ApiPolicies",
    modelProperties: {
      ...Resource.type.modelProperties,
      content: {
        serializedName: "properties.content",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const HostingEnvironmentServiceDescriptions: msRest.CompositeMapper = {
  serializedName: "HostingEnvironmentServiceDescriptions",
  type: {
    name: "Composite",
    className: "HostingEnvironmentServiceDescriptions",
    modelProperties: {
      hostingEnvironmentId: {
        serializedName: "hostingEnvironmentId",
        type: {
          name: "String"
        }
      },
      hostId: {
        serializedName: "hostId",
        type: {
          name: "String"
        }
      },
      serviceUrl: {
        serializedName: "serviceUrl",
        type: {
          name: "String"
        }
      },
      useInternalRouting: {
        serializedName: "useInternalRouting",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const BackendServiceDefinition: msRest.CompositeMapper = {
  serializedName: "BackendServiceDefinition",
  type: {
    name: "Composite",
    className: "BackendServiceDefinition",
    modelProperties: {
      ...Resource.type.modelProperties,
      serviceUrl: {
        serializedName: "properties.serviceUrl",
        type: {
          name: "String"
        }
      },
      hostingEnvironmentServiceUrls: {
        serializedName: "properties.hostingEnvironmentServiceUrls",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "HostingEnvironmentServiceDescriptions"
            }
          }
        }
      }
    }
  }
};

export const ApiOAuthSettingsParameter: msRest.CompositeMapper = {
  serializedName: "ApiOAuthSettingsParameter",
  type: {
    name: "Composite",
    className: "ApiOAuthSettingsParameter",
    modelProperties: {
      value: {
        serializedName: "value",
        type: {
          name: "String"
        }
      },
      options: {
        serializedName: "options",
        type: {
          name: "Object"
        }
      },
      uiDefinition: {
        serializedName: "uiDefinition",
        type: {
          name: "Object"
        }
      }
    }
  }
};

export const ApiOAuthSettings: msRest.CompositeMapper = {
  serializedName: "ApiOAuthSettings",
  type: {
    name: "Composite",
    className: "ApiOAuthSettings",
    modelProperties: {
      identityProvider: {
        serializedName: "identityProvider",
        type: {
          name: "String"
        }
      },
      clientId: {
        serializedName: "clientId",
        type: {
          name: "String"
        }
      },
      clientSecret: {
        serializedName: "clientSecret",
        type: {
          name: "String"
        }
      },
      scopes: {
        serializedName: "scopes",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      redirectUrl: {
        serializedName: "redirectUrl",
        type: {
          name: "String"
        }
      },
      properties: {
        serializedName: "properties",
        type: {
          name: "Object"
        }
      },
      customParameters: {
        serializedName: "customParameters",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Composite",
              className: "ApiOAuthSettingsParameter"
            }
          }
        }
      }
    }
  }
};

export const ConnectionParameter: msRest.CompositeMapper = {
  serializedName: "ConnectionParameter",
  type: {
    name: "Composite",
    className: "ConnectionParameter",
    modelProperties: {
      type: {
        serializedName: "type",
        type: {
          name: "Enum",
          allowedValues: [
            "string",
            "securestring",
            "secureobject",
            "int",
            "bool",
            "object",
            "array",
            "oauthSetting",
            "connection"
          ]
        }
      },
      defaultValue: {
        serializedName: "defaultValue",
        type: {
          name: "Object"
        }
      },
      oAuthSettings: {
        serializedName: "oAuthSettings",
        type: {
          name: "Composite",
          className: "ApiOAuthSettings"
        }
      },
      uiDefinition: {
        serializedName: "uiDefinition",
        type: {
          name: "Object"
        }
      }
    }
  }
};

export const ApiEntity: msRest.CompositeMapper = {
  serializedName: "ApiEntity",
  type: {
    name: "Composite",
    className: "ApiEntity",
    modelProperties: {
      ...Resource.type.modelProperties,
      apiEntityName: {
        serializedName: "properties.name",
        type: {
          name: "String"
        }
      },
      generalInformation: {
        serializedName: "properties.generalInformation",
        type: {
          name: "Composite",
          className: "GeneralApiInformation"
        }
      },
      path: {
        serializedName: "properties.path",
        type: {
          name: "String"
        }
      },
      runtimeUrls: {
        serializedName: "properties.runtimeUrls",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      protocols: {
        serializedName: "properties.protocols",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      policies: {
        serializedName: "properties.policies",
        type: {
          name: "Composite",
          className: "ApiPolicies"
        }
      },
      backendService: {
        serializedName: "properties.backendService",
        type: {
          name: "Composite",
          className: "BackendServiceDefinition"
        }
      },
      apiDefinitionUrl: {
        serializedName: "properties.apiDefinitionUrl",
        type: {
          name: "String"
        }
      },
      metadata: {
        serializedName: "properties.metadata",
        type: {
          name: "Object"
        }
      },
      capabilities: {
        serializedName: "properties.capabilities",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      connectionParameters: {
        serializedName: "properties.connectionParameters",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Composite",
              className: "ConnectionParameter"
            }
          }
        }
      },
      createdTime: {
        serializedName: "properties.createdTime",
        type: {
          name: "DateTime"
        }
      },
      changedTime: {
        serializedName: "properties.changedTime",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const ConnectionError: msRest.CompositeMapper = {
  serializedName: "ConnectionError",
  type: {
    name: "Composite",
    className: "ConnectionError",
    modelProperties: {
      ...Resource.type.modelProperties,
      code: {
        serializedName: "properties.code",
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "properties.message",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ConnectionStatus: msRest.CompositeMapper = {
  serializedName: "ConnectionStatus",
  type: {
    name: "Composite",
    className: "ConnectionStatus",
    modelProperties: {
      ...Resource.type.modelProperties,
      status: {
        serializedName: "properties.status",
        type: {
          name: "String"
        }
      },
      target: {
        serializedName: "properties.target",
        type: {
          name: "String"
        }
      },
      error: {
        serializedName: "properties.error",
        type: {
          name: "Composite",
          className: "ConnectionError"
        }
      }
    }
  }
};

export const CustomLoginSettingValue: msRest.CompositeMapper = {
  serializedName: "CustomLoginSettingValue",
  type: {
    name: "Composite",
    className: "CustomLoginSettingValue",
    modelProperties: {
      ...Resource.type.modelProperties,
      option: {
        serializedName: "properties.option",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ParameterCustomLoginSettingValues: msRest.CompositeMapper = {
  serializedName: "ParameterCustomLoginSettingValues",
  type: {
    name: "Composite",
    className: "ParameterCustomLoginSettingValues",
    modelProperties: {
      ...Resource.type.modelProperties,
      customParameters: {
        serializedName: "properties.customParameters",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Composite",
              className: "CustomLoginSettingValue"
            }
          }
        }
      }
    }
  }
};

export const ArmPlan: msRest.CompositeMapper = {
  serializedName: "ArmPlan",
  type: {
    name: "Composite",
    className: "ArmPlan",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      publisher: {
        serializedName: "publisher",
        type: {
          name: "String"
        }
      },
      product: {
        serializedName: "product",
        type: {
          name: "String"
        }
      },
      promotionCode: {
        serializedName: "promotionCode",
        type: {
          name: "String"
        }
      },
      version: {
        serializedName: "version",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SkuDescription: msRest.CompositeMapper = {
  serializedName: "SkuDescription",
  type: {
    name: "Composite",
    className: "SkuDescription",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      tier: {
        serializedName: "tier",
        type: {
          name: "String"
        }
      },
      size: {
        serializedName: "size",
        type: {
          name: "String"
        }
      },
      family: {
        serializedName: "family",
        type: {
          name: "String"
        }
      },
      capacity: {
        serializedName: "capacity",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const ResponseMessageEnvelopeApiEntity: msRest.CompositeMapper = {
  serializedName: "ResponseMessageEnvelope_ApiEntity_",
  type: {
    name: "Composite",
    className: "ResponseMessageEnvelopeApiEntity",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      },
      plan: {
        serializedName: "plan",
        type: {
          name: "Composite",
          className: "ArmPlan"
        }
      },
      properties: {
        serializedName: "properties",
        type: {
          name: "Composite",
          className: "ApiEntity"
        }
      },
      sku: {
        serializedName: "sku",
        type: {
          name: "Composite",
          className: "SkuDescription"
        }
      }
    }
  }
};

export const ExpandedParentApiEntity: msRest.CompositeMapper = {
  serializedName: "ExpandedParent_ApiEntity_",
  type: {
    name: "Composite",
    className: "ExpandedParentApiEntity",
    modelProperties: {
      ...Resource.type.modelProperties,
      expandedParentApiEntityId: {
        serializedName: "properties.id",
        type: {
          name: "String"
        }
      },
      entity: {
        serializedName: "properties.entity",
        type: {
          name: "Composite",
          className: "ResponseMessageEnvelopeApiEntity"
        }
      }
    }
  }
};

export const Connection: msRest.CompositeMapper = {
  serializedName: "Connection",
  type: {
    name: "Composite",
    className: "Connection",
    modelProperties: {
      ...Resource.type.modelProperties,
      connectionName: {
        serializedName: "properties.name",
        type: {
          name: "String"
        }
      },
      displayName: {
        serializedName: "properties.displayName",
        type: {
          name: "String"
        }
      },
      statuses: {
        serializedName: "properties.statuses",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ConnectionStatus"
            }
          }
        }
      },
      customParameterValues: {
        serializedName: "properties.customParameterValues",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Composite",
              className: "ParameterCustomLoginSettingValues"
            }
          }
        }
      },
      tenantId: {
        serializedName: "properties.tenantId",
        type: {
          name: "String"
        }
      },
      parameterValues: {
        serializedName: "properties.parameterValues",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Object"
            }
          }
        }
      },
      nonSecretParameterValues: {
        serializedName: "properties.nonSecretParameterValues",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Object"
            }
          }
        }
      },
      metadata: {
        serializedName: "properties.metadata",
        type: {
          name: "Object"
        }
      },
      firstExpirationTime: {
        serializedName: "properties.firstExpirationTime",
        type: {
          name: "DateTime"
        }
      },
      keywords: {
        serializedName: "properties.keywords",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      createdTime: {
        serializedName: "properties.createdTime",
        type: {
          name: "DateTime"
        }
      },
      changedTime: {
        serializedName: "properties.changedTime",
        type: {
          name: "DateTime"
        }
      },
      api: {
        serializedName: "properties.api",
        type: {
          name: "Composite",
          className: "ExpandedParentApiEntity"
        }
      }
    }
  }
};

export const ConsentLinkInputParameter: msRest.CompositeMapper = {
  serializedName: "ConsentLinkInputParameter",
  type: {
    name: "Composite",
    className: "ConsentLinkInputParameter",
    modelProperties: {
      principalType: {
        serializedName: "principalType",
        type: {
          name: "Enum",
          allowedValues: [
            "ActiveDirectory",
            "Connection",
            "MicrosoftAccount"
          ]
        }
      },
      tenantId: {
        serializedName: "tenantId",
        type: {
          name: "String"
        }
      },
      objectId: {
        serializedName: "objectId",
        type: {
          name: "String"
        }
      },
      parameterName: {
        serializedName: "parameterName",
        type: {
          name: "String"
        }
      },
      redirectUrl: {
        serializedName: "redirectUrl",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ConsentLinkInput: msRest.CompositeMapper = {
  serializedName: "ConsentLinkInput",
  type: {
    name: "Composite",
    className: "ConsentLinkInput",
    modelProperties: {
      ...Resource.type.modelProperties,
      parameters: {
        serializedName: "properties.parameters",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ConsentLinkInputParameter"
            }
          }
        }
      }
    }
  }
};

export const ConsentLink: msRest.CompositeMapper = {
  serializedName: "ConsentLink",
  type: {
    name: "Composite",
    className: "ConsentLink",
    modelProperties: {
      link: {
        serializedName: "link",
        type: {
          name: "String"
        }
      },
      firstPartyLoginUri: {
        serializedName: "firstPartyLoginUri",
        type: {
          name: "String"
        }
      },
      displayName: {
        serializedName: "displayName",
        type: {
          name: "String"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "Enum",
          allowedValues: [
            "Unauthenticated",
            "Authenticated",
            "Error"
          ]
        }
      }
    }
  }
};

export const ConsentLinkPayload: msRest.CompositeMapper = {
  serializedName: "ConsentLinkPayload",
  type: {
    name: "Composite",
    className: "ConsentLinkPayload",
    modelProperties: {
      value: {
        serializedName: "value",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ConsentLink"
            }
          }
        }
      }
    }
  }
};

export const ListConnectionKeysInput: msRest.CompositeMapper = {
  serializedName: "ListConnectionKeysInput",
  type: {
    name: "Composite",
    className: "ListConnectionKeysInput",
    modelProperties: {
      ...Resource.type.modelProperties,
      validityTimeSpan: {
        serializedName: "properties.validityTimeSpan",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ConnectionSecrets: msRest.CompositeMapper = {
  serializedName: "ConnectionSecrets",
  type: {
    name: "Composite",
    className: "ConnectionSecrets",
    modelProperties: {
      parameterValues: {
        serializedName: "parameterValues",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Object"
            }
          }
        }
      },
      connectionKey: {
        serializedName: "connectionKey",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ConfirmConsentCodeInput: msRest.CompositeMapper = {
  serializedName: "ConfirmConsentCodeInput",
  type: {
    name: "Composite",
    className: "ConfirmConsentCodeInput",
    modelProperties: {
      ...Resource.type.modelProperties,
      principalType: {
        serializedName: "properties.principalType",
        type: {
          name: "Enum",
          allowedValues: [
            "ActiveDirectory",
            "Connection",
            "MicrosoftAccount"
          ]
        }
      },
      tenantId: {
        serializedName: "properties.tenantId",
        type: {
          name: "String"
        }
      },
      objectId: {
        serializedName: "properties.objectId",
        type: {
          name: "String"
        }
      },
      code: {
        serializedName: "properties.code",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ApisCollection: msRest.CompositeMapper = {
  serializedName: "ApisCollection",
  type: {
    name: "Composite",
    className: "ApisCollection",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ApiEntity"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ConnectionCollection: msRest.CompositeMapper = {
  serializedName: "ConnectionCollection",
  type: {
    name: "Composite",
    className: "ConnectionCollection",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Connection"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};
