/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/managedApisMappers";
import * as Parameters from "../models/parameters";
import { WebSiteManagementClientContext } from "../webSiteManagementClientContext";

/** Class representing a ManagedApis. */
export class ManagedApis {
  private readonly client: WebSiteManagementClientContext;

  /**
   * Create a ManagedApis.
   * @param {WebSiteManagementClientContext} client Reference to the service client.
   */
  constructor(client: WebSiteManagementClientContext) {
    this.client = client;
  }

  /**
   * Gets a list of managed APIs.
   * @summary List managed Apis
   * @param location The location.
   * @param [options] The optional parameters
   * @returns Promise<Models.ManagedApisListResponse>
   */
  list(location: string, options?: msRest.RequestOptionsBase): Promise<Models.ManagedApisListResponse>;
  /**
   * @param location The location.
   * @param callback The callback
   */
  list(location: string, callback: msRest.ServiceCallback<Models.ApisCollection>): void;
  /**
   * @param location The location.
   * @param options The optional parameters
   * @param callback The callback
   */
  list(location: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ApisCollection>): void;
  list(location: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.ApisCollection>, callback?: msRest.ServiceCallback<Models.ApisCollection>): Promise<Models.ManagedApisListResponse> {
    return this.client.sendOperationRequest(
      {
        location,
        options
      },
      listOperationSpec,
      callback) as Promise<Models.ManagedApisListResponse>;
  }

  /**
   * Gets a managed API.
   * @summary Get managed API
   * @param location The location.
   * @param apiName The managed API name.
   * @param [options] The optional parameters
   * @returns Promise<Models.ManagedApisGetResponse>
   */
  get(location: string, apiName: string, options?: Models.ManagedApisGetOptionalParams): Promise<Models.ManagedApisGetResponse>;
  /**
   * @param location The location.
   * @param apiName The managed API name.
   * @param callback The callback
   */
  get(location: string, apiName: string, callback: msRest.ServiceCallback<Models.ApiEntity>): void;
  /**
   * @param location The location.
   * @param apiName The managed API name.
   * @param options The optional parameters
   * @param callback The callback
   */
  get(location: string, apiName: string, options: Models.ManagedApisGetOptionalParams, callback: msRest.ServiceCallback<Models.ApiEntity>): void;
  get(location: string, apiName: string, options?: Models.ManagedApisGetOptionalParams | msRest.ServiceCallback<Models.ApiEntity>, callback?: msRest.ServiceCallback<Models.ApiEntity>): Promise<Models.ManagedApisGetResponse> {
    return this.client.sendOperationRequest(
      {
        location,
        apiName,
        options
      },
      getOperationSpec,
      callback) as Promise<Models.ManagedApisGetResponse>;
  }

  /**
   * Gets a list of managed APIs.
   * @summary List managed Apis
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param [options] The optional parameters
   * @returns Promise<Models.ManagedApisListNextResponse>
   */
  listNext(nextPageLink: string, options?: msRest.RequestOptionsBase): Promise<Models.ManagedApisListNextResponse>;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param callback The callback
   */
  listNext(nextPageLink: string, callback: msRest.ServiceCallback<Models.ApisCollection>): void;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param options The optional parameters
   * @param callback The callback
   */
  listNext(nextPageLink: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ApisCollection>): void;
  listNext(nextPageLink: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.ApisCollection>, callback?: msRest.ServiceCallback<Models.ApisCollection>): Promise<Models.ManagedApisListNextResponse> {
    return this.client.sendOperationRequest(
      {
        nextPageLink,
        options
      },
      listNextOperationSpec,
      callback) as Promise<Models.ManagedApisListNextResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/providers/Microsoft.Web/locations/{location}/managedApis",
  urlParameters: [
    Parameters.location,
    Parameters.subscriptionId
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ApisCollection
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const getOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/providers/Microsoft.Web/locations/{location}/managedApis/{apiName}",
  urlParameters: [
    Parameters.location,
    Parameters.apiName,
    Parameters.subscriptionId
  ],
  queryParameters: [
    Parameters.exportParameter,
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ApiEntity
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const listNextOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  baseUrl: "https://management.azure.com",
  path: "{nextLink}",
  urlParameters: [
    Parameters.nextPageLink
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ApisCollection
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};
